development:
  secret_key_base: 73dbb51133b6fe0bf9c40e8b80184f7996b172f76f5b8fa78671d8c5319cb23355ac89c7ff474b76c262a7fa5c3b10edea02dd93c901b212064a4dc561011321
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 9af06f6718e2c8e8293e6c76d9158cff1480e8eb3fc1eb6bc12af6a0f96340e00542f12cd929019d44b75049b06534d0b71da0fc4129c9f40f2eafab906a5034

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
